# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af9d5b545fe72a3df25376b30c8fc912e8289fd4993f277ef0a389e4027c2feace7920d383092ac32afc45a76889c2c8a651ed4f7eba41d28741539eed97f665

test:
  secret_key_base: 81d6c5334fdc576c624ed18f86e2690be51b555dd265bd89c8f44c9070fa926ee2a1cbfc402bd41ef412fb20b656967a700fa0378c9346c741ccf9ca48191ca0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
